### PR TITLE
Upgrade for use with ember-cli 1.13.8

### PR DESCRIPTION
**Pull request by akshayrawat**

### CODE REVIEW

**Comment by akshayrawat** [comment]
@dlorson I needed this addon on a new ember app and had to upgrade it a bit. Hope it makes it to master!

**Comment by akshayrawat** [comment]
@dlorson Let me know what you think. I'm currently using my branch in production and would like to see this merged in. Thanks!

**Comment by dlorson** [comment]
Great, thanks @akshayrawat for your improvements!

**Comment by akshayrawat** [comment]
@dlorson Awesome! Can you run `npm publish` as well.

**Pull request merged**
